### PR TITLE
feat: update medium Avatar and circle-md sizes to 40px

### PR DESCRIPTION
**Pull request by ghost**
## 🖼 Context

https://transferwise.atlassian.net/jira/software/projects/DS/boards/277?label=Web&selectedIssue=DS-1542

## 🚀 Changes

- Update `@avatar-diameter-md` to `40px` in `packages/components/src/avatar/Avatar.less`
- Update `@circle-sm-diameter` to `40px` in `packages/css/src/less/circles.less`

## ✅ Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

### CODE REVIEW

**Comment by sbrandwoo** [comment]
Is there a discussion thread about this?

**Comment by sbrandwoo** [comment]
We use 48px avatars extensively around the Balance product, and we would have to re-design the Jar avatar in order to work at 40px. What's the justification for this change?

**Comment by matebek-tw** [comment]
> We use 48px avatars extensively around the Balance product, and we would have to re-design the Jar avatar in order to work at 40px. What's the justification for this change?

The reason is that our designs got updated to use `40px` for the medium sized avatars on the NavigationOption (https://neptune.wise.com/components/navigation-option/) so now we have 2 different avatar sizes. Wanted to see the implications of updating the medium sized Avatar everywhere to `40px` as well (therefore this PR), or if we should come up with different solutions for the Options.

**Comment by sbrandwoo** [comment]
We need to support correctly sized avatars in navigation options too:
image

**Review by dozortsev — APPROVED** [review]

**Review by helendurranttw — CHANGES_REQUESTED** [review]
I don't think this should be merged without consultation with the other platforms. There are inconsistencies that should be addressed - in Figma there are 4 sizes of Avatar (including both 40 and 48px) and on iOS 40px is considered small.

I recommend agreeing on scales with all platforms before progressing.

**Comment by matebek-tw** [comment]
We agreed with designers that there should be more sizes supported on the platform, and we should use numeric values to define Avatar sizes e.g. `Size.40`.

CleanShot 2022-02-01 at 10 48 39@2x

**Comment by richardmccartney** [comment]
Closing this PR for the time being until we pick up any new component work on Avatars 👍

**Pull request closed without merging**
