### PR TITLE
feat(FlowNavigation): upgraded icons

### PR DESCRIPTION
**Pull request by sergonius**
## 🖼 Context
Migrating send-flow to the new icons.
https://transferwise.atlassian.net/browse/SEND-1065

## 🚀 Changes
Replaced a few icons and added styles to fix positioning.

## ✅ Checklist
- [ ] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/master/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

### Before
b4

### After
a4

### CODE REVIEW

**Comment by sergonius** [comment]
> Hey @sergonius , this update needs to wait for the new icons to be released. We can't update the icons only for this component. New Icons have currently been merged into beta branch. Maybe we can merge this one into beta.

Sounds good. Is there an ETA?

**Comment by dozortsev** [comment]
> ..Maybe we can merge this one into beta.

@andreapiras we can't and we don't need, as in `beta` branch this component already migrated on new icons

**Comment by andreapiras** [comment]
> > ..Maybe we can merge this one into beta.
> 
> @andreapiras we can't and we don't need, as in `beta` branch this component already migrated on new icons

Yeah but does the beta branch contains these new changes for FlowNavigation? If yes ignore me, if not maybe we should merge it

**Comment by dozortsev** [comment]
> Yeah but does the beta branch contains these new changes for FlowNavigation?

@andreapiras which new changes?

**Comment by andreapiras** [comment]
> > Yeah but does the beta branch contains these new changes for FlowNavigation?
> 
> @andreapiras which new changes?

When you merged your changes into beta branch, avatarWrapper didn't exist. We should take into account these changes too

**Pull request closed without merging**
