### PR TITLE
perf: remove propTypes from components and dynamic-flows build

### PR DESCRIPTION
**Pull request by jackleslie**
☝️ make the title meaningful and follow conventional commits standards

## 📎 Jira ticket
N/A

## ❓ Context  
[This babel plugin](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) removes `propTypes` declarations from production builds (it was featured in [this Google Chrome list](https://github.com/GoogleChromeLabs/webpack-libs-optimizations#react) of recommendations for webpack library optimisations) and thought I'd make a PR. It's also used internally by [Next.js](https://github.com/vercel/next.js/blob/e125d905a0dd93d247c6122d349c2c90268f0713/packages/next/build/babel/preset.ts#L176) to reduce build sizes (hence why it was already in the `yarn.lock` file)

## 🚀 Changes 
Adds `babel-plugin-transform-react-remove-prop-types` to `babel.config.js` in the `components` and `dynamic-flows` packages. It reduces bundles sizes (in filesystem) as follows:

### `components`
- `es/no-polyfill`: `264kb` -> `242kb`
- `es/polyfill`: `272kb` -> `250kb`
- `umd/no-polyfill`: `340kb` -> `323kb`
- `umd/polyfill`: `381kb` -> `364kb`

### `dynamic-flows`
- `es/no-polyfill`: `127kb` -> `118kb`
- `es/polyfill`: `132kb` -> `123kb`

## 💬 Considerations 
This only applies to functional components, class components which use `static` propTypes won't benefit from this. In the Google Chrome list it is flagged as "safe to use by default". I didn't do any testing beyond symlinking locally and running storybook.

## ✅ Checklist

- [ ] All changes are covered by tests
- [ ] All changes have been crossbrowser checked, especially IE11
- [ ] The changes are covered in docs

### CODE REVIEW

**Comment by andreapiras** [comment]
Hey @jackleslie nice one!! (...as usual). We have a new package called dynamic flow inside neptune web it would be great if you can add it there too. Let me know if you can't and we can add it ourselves. Thanks for contributing

**Comment by jackleslie** [comment]
No problem, that's me added it @andreapiras! 😃  I noticed there are no `umd` builds for `dynamic-flows` - how come?

**Comment by andreapiras** [comment]
Hey @jackleslie we had to revert that because the test was failing. FormControl.spec is failing because is relying to propTypes, would you mind have a look and then we can remerge :)

**Comment by jackleslie** [comment]
@andreapiras second attempt in #420

**Pull request merged**
