### PR TITLE
C20-2635: Expose selectprops for dropdown components

### PR DESCRIPTION
**Pull request by jonathan-barnes-wise**
## Context

Follows on from #1443 and #1445.

Apologies for this being the third PR into this repo for this ticket, hopefully it's the last instalment of this epic trilogy.
🤞 😅 🤞 

This PR adds the ability to pass props to any `Select` controls which are rendered by components composing `Select`  (`DateInput`, `MoneyInput` and `PhoneNumberInput`). Also, it's currently possible to have duplicate ids on the page if multiple `Select` components are rendered with no explicit `id`s set. This should hopefully fix that.

[C20-2635](https://transferwise.atlassian.net/browse/C20-2635) Ticket with initial a11y finding and remediation plan.

## Changes

 
- ~~Adds `lodash.uniqueid` dependency (I tried to avoid this, and considered alternative libs (uuid/v4), but this repo already uses lodash deps and felt it'd be a bit more consistent. No vulns reported by `yarn audit --production`).~~
- Add [simple fallback id generation](https://github.com/transferwise/neptune-web/pull/1448/files#diff-29d0efb3fed45db7c0cd30b2bd9190372a2db9f970e9ee367c106d230e115665R24) for `Select` component avoiding [possible a11y violation ](https://web.dev/duplicate-id-aria/).
- Expose `selectProps` for `DateInput`, `MoneyInput` and `PhoneNumberInput`

## Considerations / Results

Happy to consider alternatives for the `lodash.uniqueid` addition, feedback welcomed 👍 

## Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

### CODE REVIEW

**Review by richardmccartney — CHANGES_REQUESTED** [review]
Since this PR was opened the `Select` component has gone through a major refactor. Could you ensure we rebase that work on to this branch and then re-apply your changes 👍

**Comment by jonathan-barnes-wise** [comment]
@richardmccartney Thanks for reviewing, comment addressed and branch rebased onto `main` 👍

**Comment by jonathan-barnes-wise** [comment]
Have also amended the changelog to include `role` changes for the `<Select>` component as a result of [this discussion](https://wise.slack.com/archives/CJNBX9CP6/p1655473864149249), aware it's auto-generated and I can't retroactively create a breaking change so let me know if this is alright/any alternatives.

**Review by richardmccartney — APPROVED** [review]
Thanks for the changes to the component, before merging lets release a beta of this change and ensure it works as expected within a few web apps 👍

**Comment by jonathan-barnes-wise** [comment]
> Thanks for the changes to the component, before merging lets release a beta of this change and ensure it works as expected within a few web apps 👍

I'm aware the `<Select role="combobox">` change (#1445) has caused a couple of issues due to missing functionality that's being added in this PR to ensure safe `id` generation for elements.

However, the beta build created by this PR has been used on the Wise homepage with no reported issues and has worked as expected for a couple of weeks now.

Let me know if there's anything else I need to do here :v:

**Comment by richardmccartney** [comment]
Hi @jonathan-barnes-wise can we rebase and sort this PR out and then get it landed this week?

**Comment by jonathan-barnes-wise** [comment]
> Hi @jonathan-barnes-wise can we rebase and sort this PR out and then get it landed this week?

Rebase is a noop, git says branch is up to date 👍

**Pull request merged**
