### PR TITLE
Add color tokens to docs

### PR DESCRIPTION
**Pull request by nabaroa**
## 📎 Jira ticket
https://transferwise.atlassian.net/browse/DS-233

## 🚀 Changes 
Rescue color documentation and add it to docs

imagen

## 💬 Considerations 
Are we going to add new branding colors to this docs?

## ✅ Checklist

- [ ] All changes are covered by tests
- [ ] The changes are covered in docs
- [ ] The commits follow conventional commits standards

### CODE REVIEW

**Comment by oliverviljamaa** [comment]
_Colour_ vs _color_ — should we aim for consistency here?

**Comment by gusso** [comment]
> _Colours_ vs _color_ — should we aim for consistency here?

Yea this one is tricky, because we definitely don't want to start writing `colour` in code, right? Conflicting with the `color` property in css, for example, sounds like a bad idea.

Do we make the effort of writing `colour` whenever we're using plain text communication, or do we standardise `color` everywhere? But then, we should probably commit to writing all Neptune documentation in the same locale, so we could decide to write all documentation in US English 😱

**Comment by nabaroa** [comment]
I´ll go through Figma colour foundations (https://www.figma.com/file/DUUEFGnfEAWFO2KEYDIL7mfr/Neptune---Foundations?node-id=205%3A297) and try to maintain consistency with tokens naming, so wait until next iteration to review this PR, please. Thanks 🙇‍♀

**Comment by helendurranttw** [comment]
Colours are now documented in `next`, coming soon to `master`!

**Pull request closed without merging**
